
set(TUVOKDATACONVERTER_VERSION   1.0.0 )
set(TUVOKDATACONVERTER_REPO_URL  https://github.com/bilgili/TuvokDataConverter.git )
set(TUVOKDATACONVERTER_REPO_TAG  master )
set(TUVOKDATACONVERTER_DEPENDS   REQUIRED Tuvok )
set(TUVOKDATACONVERTER_NOTEST    ON)
set(TUVOKDATACONVERTER_OPTIONAL  ON)


if(CI_BUILD_COMMIT)
  set(TUVOKDATACONVERTER_REPO_TAG ${CI_BUILD_COMMIT})
else()
  set(TUVOKDATACONVERTER_REPO_TAG master)
endif()
set(TUVOKDATACONVERTER_FORCE_BUILD ON)
set(TUVOKDATACONVERTER_SOURCE ${CMAKE_SOURCE_DIR})
